### ISSUE TITLE
clone after error! branch matser and 2.8  Cannot compile

### ISSUE THREAD

**Issue by KnightYyj** [wjkhappy14/Abp.VNext.Hello#6]
![image](https://user-images.githubusercontent.com/26918295/83388423-01d78900-a421-11ea-842c-d17f3d240ccd.png)

**Comment by KnightYyj** [comment]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS0535	'“FakeCurrentPrincipalAccessor”不实现接口成员“ICurrentPrincipalAccessor.Change(ClaimsPrincipal)”	Abp.VNext.Hello.TestBase	 
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS0234	命名空间“Abp.VNext.Hello”中不存在类型或命名空间名“Users”(是否缺少程序集引用?)	Abp.VNext.Hello.EntityFrameworkCore.Tests

**Comment by wjkhappy14** [comment]
now i have  removed the test proj, so no any errors more .
